blueprint:
  name: Custom Door-activated Light
  description: Turn on a light when door is oppened. Turn off when closed
  domain: automation
  source_url: https://github.com/Dodoww/HomeAssistantCustomBlueprints/blob/main/DoorLightActivated.yaml
  input:
    state_from: 
      name: State of sensor when light is turned off
      description: "The state of sensor when light is off"
      default: "off"
      selector:
        select:
          options:
            - label: "ON"
              value: "on"
            - label: "OFF"
              value: "off"
    state_to:
      name: State of sensor when light is turned on
      description: "The state of sensor when light is on"
      default: "on"
      selector:
        select:
          options:
            - label: "ON"
              value: "on"
            - label: "OFF"
              value: "off"
      
    door_entity:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    time_start:
      name: Schedule start time
      description: Automation only runs after this time.
      default: "00:00:00"
      selector:
        time:
    time_stop:
      name: Schedule start stop
      description: Automation does not run after this time.
      default: "00:00:00"
      selector:
        time:
    on_action:
      name: Custom Action To Run (Optional)
      description: Select actions to run when door is opened.
      default: []
      selector:
        action: {}
    night_brightness:
      name: Night brightness
      description: Brightness, in night mode mode
      default: 50
      selector:
        number:
          min: 1.0
          max: 100.0
          step: 1.0
          mode: slider

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input door_entity
  from: !input state_from
  to: !input state_to

condition:
  - condition: time
    after: !input time_start
    before: !input time_stop

action:
  - alias: "Turn on the light"
    service: light.turn_on
    data:
      brightness_pct: !input night_brightness
    target: !input light_target
  - alias: "Wait until there is no door from device"
    wait_for_trigger:
      platform: state
      entity_id: !input door_entity
      from: !input state_to
      to: !input state_from
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
  - choose: []
    default: !input 'on_action'