blueprint:
  name: Custom Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/Dodoww/HomeAssistantCustomBlueprints/blob/main/MotionLightActivated.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    time_start:
      name: Schedule start time
      description: Automation only runs after this time.
      selector:
        time:
    time_stop:
      name: Schedule start stop
      description: Automation does not run after this time.
      selector:
        time:
    notifcation_title:
      name: Notifcation Title
      description: Title of telegram notification
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message of telegram notification
      selector:
        text:
    brightness:
      name: Brightness
      description: Brightness
      default: 50
      selector:
        number:
          min: 1.0
          max: 100.0
          step: 1.0
          mode: slider
# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: time
    after: !input time_start
    before: !input time_stop

action:
  - alias: "Turn on the light"
    service: light.turn_on
    data:
      brightness_pct: !input brightness
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
  - alias: Send Notification
    service: notify.history_notifs
    data:
      title: !input notifcation_title
      message: !input notification_message
